### ISSUE TITLE
Labels are placed AFTER clustering

### ISSUE THREAD

**Issue by SamGG** [alexploner/Heatplus#5]
Hi,
Thanks for your very useful package, especially concerning the continuous annotation.
The labels argument drives me mad, because I didn't understand that those labels are placed after the clustering, ie clustering does not reorganize them. I thought 
I think you should drop a short message about that.
Best.

```r
# Some data
data("iris")
dmat = as.matrix(iris[c(1:9, 51:59, 101:109),-5])
row.names(dmat) = iris[c(1:9, 51:59, 101:109),5]
dmat = dmat - mean(dmat)
# Row labels are organised with clustering
plot(annHeatmap(x = dmat, scale = "none", breaks = seq(-5, 5, 0.5), annotation = NULL, dendrogram = list(Col=list(status="no"), Row=list(status="yes")), col = colorRampPalette(c("Blue3", "White", "Red3"))))
# Clustering is ignored (versicolor and viriginica are no more mixed)
plot(annHeatmap(x = dmat, scale = "none", breaks = seq(-5, 5, 0.5), annotation = NULL, dendrogram = list(Col=list(status="no"), Row=list(status="yes")), labels = list(Row = list(labels = rownames(dmat))), col = colorRampPalette(c("Blue3", "White", "Red3"))))
```

**Comment by alexploner** [comment]
Thanks for the feedback and agreed, that can take you by surprise. I have added a warning and an alternative solution (i.e. settting the row / column names of the data matrix) to the documentation of `annHeatmap`.

Your example code is appreciated, with two caveats:
1. It's too elaborate to be easily readable: details like color, cuts etc. are not really relevant for the point you are trying to make.
2. Slightly more serious, it does not work: the `annotation=NULL` argument leads to a cryptic error when executing the code. I have therefore updated the package to check that argument `annotation`  to function `annHeatmap`  is a valid data frame, so now at least the problem is clear. 

    Soooo... thanks again :-)

**Comment by SamGG** [comment]
Sorry for the code. I don't know why I thought it was working. Right, it is clearly not straight to the point.
I switched to the use of the row and column names of the matrix.
Thanks for your attention.

**Comment by alexploner** [comment]
No worries, I'd rather have wordy code than none (generally speaking). 

Wrt to the bug: at the end, it helped improve the code, so really, it has made the world an (infinitesimally) better place ;-)
