### ISSUE TITLE
distance of dendrogram when no labels used

### ISSUE THREAD

**Issue by piatekmj** [alexploner/Heatplus#8]
I've noticed that when row labels are disabled (NULL) then there is no distance between the heatmap and the row dendrogram. It would be great if there was for example an 'nrow' parameter we could use to manipulate position of dendrogram when we don't use labels. I also see potential use for 'side' switch for dendrogram.

In order to overcome this, I have used very small cex value for row labels in companion with 'nrow'.
That is the only way known to me, that allows for controlling position of dendrogram, which otherwise is touching the heatmap.

Other than that, this is a really cool package that I started to use more and more.

**Comment by alexploner** [comment]
I'm not quite sure what you have in mind, seeing as you have not added an example, but there is both a `nrow` and a `side`  parameter that can be set via argument `labels`, see `?annHeatmap2`. 

Admittedly, the `nrow` parameter does not work if there are no column- or rownames, so the hack for now is to just set the row/column names to a blank or empty string, see code below. 

I agree that having `nrow` work even for missing row/colnames would be consistent behavior, so I'll leave this issue open for now and will add this (with low priority though).

```{r}
##Example: any space you want between dendrgram and heatmap
library(annHeatmap)

## Standard example from ?annHeatmap
set.seed(219)
mat = matrix(rnorm(100), ncol=5)
ann = data.frame(Class=c("A","A","B","A","B"))

## Set colum names to empty string
colnames(mat) = rep("", ncol(mat))

## Small distance
map1 = annHeatmap(mat, ann, labels=list(nrow=1))
plot(map1)

## Large distance
map1 = annHeatmap(mat, ann, labels=list(nrow=3))
plot(map1)

## Fractional distance
map1 = annHeatmap(mat, ann, labels=list(nrow=1.5))
plot(map1)
```

**Comment by piatekmj** [comment]
Thank you for your response.
Using your example I'm able to reproduce my problem. I am not concerned about the column labels as much as I am about row labels.

```
## Standard example from ?annHeatmap
set.seed(219)
mat = matrix(rnorm(100), ncol=5)
ann = data.frame(Class=c("A","A","B","A","B"))

## Set colum names to empty string
colnames(mat) = rep("", ncol(mat))
rownames(mat) = rep("", nrow(mat))
## Small distance
map1 = annHeatmap(mat, ann,
labels=list(nrow=2),
dendrogram=list(Col=list(lwd=0.5), Row=list(lwd=0.5))
)
plot(map1)
```
Is there any advice you can provide with regards to the above example?

**Comment by alexploner** [comment]
Sorry, I mis-interpreted your original mail (which is why example code is so useful). 

Your original statement is not correct: the row dendrogram has the same distance to the heatmap, regardless of whether there are rownames or not. However, there is an unexpected side-effect in `plot.annHeatmap`: if you run the code below on a fresh R session (no plot window open), then the first plot will have a little gap between heatmap and row dendrogram, but the second one and all others afterward will directly touch the heatmap.
```{r}
## Data without row or column names
library(Heatplus)
set.seed(219)
mat = matrix(rnorm(100), ncol=5)
ann = data.frame(Class=c("A","A","B","A","B"))
dimnames(mat) = NULL
## Turn off all current plotting devices
while(!is.null(dev.list())) dev.off()
map1 = annHeatmap(mat, ann, dendrogram=list(status="yes"))
## This should have a little gap between row dendrogram and heatmap
plot(map1)
## Here the row dendrogram should touch the heatmap
plot(map1)

## Data with row and column names: same thing
mat2 = mat
rownames(mat2) = LETTERS[1:nrow(mat2)]
colnames(mat2) = letters[1:ncol(mat2)]
map2 = annHeatmap(mat2, ann, dendrogram=list(status="yes"))
## Off with the device - gap
while(!is.null(dev.list())) dev.off()
plot(map2)
## These should touch
plot(map2)
plot(map1)
```
This is of course clearly a bug, and I'll fix it ASAP. 

In the meantime, if you want the little gap, just plot to a fresh device (which means that you should be ok when plotting to a file, unless you generate multi-page files). If you want to vary the distance between dendrogram and heatmap beyond that little gap, there is a hack which works if you don't have any row labels, or don't mind having your row labels on the left side:
```{r}
## Hackish: this varies the distance between dendrogram and 
## heatmap at the price of either no row labels.... 
mat3 = mat2
rownames(mat3) = rep("", nrow(mat3))
map3 = annHeatmap(mat3, ann, dendrogram = list(status="yes"), 
                  labels = list(Row = list(side=2, nrow=2)))
plot(map3)

## ... or row labels on the left
map4 = annHeatmap(mat2, ann, dendrogram = list(status="yes"), 
                  labels = list(Row = list(side=2, nrow=2)))
plot(map4)
```
I'll still go over the defaults for the these distances, and will try for more consistency and flexibility, but as mentioned above, with less urgency.

**Comment by alexploner** [comment]
I have finally gotten around to adding the appropriate `on.exit`-call to `plot.annHeatmap`. Repeated execution of `plot(map1)` in the example above should now generate the same plot every time, with a small gap between the dendrograms and the heatmap. 

No update for default distances in case of missing row- or column names; I'll move this to an issue of its own.
